HOST: http://www.google.com/

--- S2 Sample REST API v1 ---

---
The S2 API is organized around REST.  The API is designed to have predictable, resource oriented 
URLs and use HTTP response codes to indicate errors. The REST API is a user interface for developers and 
appropriate effort has been applied to ensure it's not just functional but pleasant to use.
---

--
NAS Location
An object responsible for representing a Network-attached storage (NAS) connection.
--

Create a NAS Location
POST /v1/csv/nas-locations
> Accept: application/json
> Content-Type: application/json
{ "computerName": "DRServer001",  "serverIp" : "192.11.99.0", "shareName" : “spare_share” }
< 201
< Content-Type: application/json
{ "id": 12, "computerName": "DRServer001",  "serverIp" : "192.11.99.0", "shareName" : “spare_hare” }

Get a NAS Location
GET /v1/csv/nas-locations/2
> Accept: application/json
< 200
< Content-Type: application/json
{
    data: { 
        "id": 2, 
        "computerName": "SAN-Slush-Server",  
        "serverIp" : "192.6.99.0", 
        "shareName" : “productOne” },
    httpStatus: 200 
}




